### ISSUE TITLE
:tada: 发布页面

### ISSUE THREAD

**Issue by james-curtis** [Cow-Coder/cow-Low-code#68]
~~我的思路是，预览可以抽离出来成一个npm包，然后发布页面就相当于是直接构建这个npm包~~
我的思路是，预览可以抽离出来成一个项目，然后发布页面就相当于是直接构建这个项目
由于要把物料组件做成预览项目和编辑器项目公用的库，所以需要用monorepo架构。
这里我们同element-plus一样，到时候改用pnpm实现monorepo

link #68

**Comment by Yziyan** [comment]
是直接给他打包构建好吗？

**Comment by james-curtis** [comment]
> 是直接给他打包构建好吗？

不用

参考这个https://github.com/qq9068149/AS-Editor-H5
